#ifndef APP_ERRORS_H
#define APP_ERRORS_H

#include <esp_err.h>

// Custom error codes
#define APP_ERR_INVALID_CONFIG (ESP_ERR_BASE + 0x100)
#define APP_ERR_NVS_READ (ESP_ERR_BASE + 0x101)
#define APP_ERR_NVS_WRITE (ESP_ERR_BASE + 0x102)
#define APP_ERR_WIFI_CONNECT (ESP_ERR_BASE + 0x103)
#define APP_ERR_MQTT_CONNECT (ESP_ERR_BASE + 0x104)
#define APP_ERR_BLE_INIT (ESP_ERR_BASE + 0x105)
#define APP_ERR_SENSOR_READ (ESP_ERR_BASE + 0x106)
#define APP_ERR_JSON_SERIALIZE (ESP_ERR_BASE + 0x107)
#define APP_ERR_JSON_DESERIALIZE (ESP_ERR_BASE + 0x108)

#endif // APP_ERRORS_H
